services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PG_VERSION=17 # Specify the version of database server, major versions has to be the same
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      app_db:
        condition: service_healthy
    restart: unless-stopped

  app_db:
    container_name: api-db
    image: "postgres:17"
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge